global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "product-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["product-service:8081"]

  - job_name: "cart-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["cart-service:8080"]
